academia/urls.py
from django.conf.urls import patterns, include, url
from academia.views import HomeView, CapituloListView, RecursoListView, PostListView
from academia import views

urlpatterns = [
    url(r'^$', HomeView.as_view() ),
    url(r'^capitulos/', CapituloListView.as_view() ),
    url(r'^material/', RecursoListView.as_view() ),
    url(r'^blog/$', PostListView.as_view() ),
    url(r'^blog/post/(?P<pk>\d+)/$', views.Post_detail, name='post_detalles',),
    url(r'^blog/add/(?P<pk>\d+)/$', views.Comentario_create, name='comentario_crear'),
]

cija/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^markdown/', include("django_markdown.urls")),
	url(r'^academia/', include("academia.urls")),
	url(r'^enfermeria/', include("enfermeria.urls")),
    url(r'^admin/', include(admin.site.urls)),
)

enfermeria/urls.py
from django.conf.urls import patterns, include, url
from enfermeria.views import HomeView, MenuView
from enfermeria import views

urlpatterns = [
    url(r'^$', HomeView.as_view() ),
    url(r'^menu/', views.Menu_index, name='menu' ),
]

academia/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django_markdown.models import MarkdownField

class Capitulo(models.Model):
    titulo = models.CharField(max_length=100)
    objetivo = MarkdownField()

    def __unicode__(self):
    	return self.titulo

class Recurso(models.Model):
	capitulo = models.ForeignKey(Capitulo)
	descripcion = models.CharField(max_length=100)
	url = models.CharField(max_length=100)
	fecha = models.DateField(auto_now=True)

	def __unicode__(self):
		return self.descripcion

class Usuario(models.Model):
    nombre = models.CharField(max_length=100)
    email = models.EmailField()

    def __unicode__(self):
        return self.nombre

class Post(models.Model):
    encabezado = models.CharField(max_length=100)
    usuario = models.ForeignKey(Usuario)
    fecha = models.DateField(auto_now=True)
    cuerpo = MarkdownField()

    def __unicode__(self):
        return self.encabezado

    def  get_absolute_url(self):
        return reverse('post_detalles', kwargs = {'pk':self.id})

    class Meta:
        ordering = ["-id"]

class Comentario(models.Model):
    usuario = models.CharField(max_length=100)
    comentario = models.TextField()
    post = models.ForeignKey(Post)
    fecha = models.DateField(auto_now=True)

    def __unicode__(self):
        return self.usuario

    class Meta:
        ordering = ["-id"]

enfermeria/models.py
from django.db import models

class Medicamento(models.Model):
    concepto = models.CharField(max_length=100)
    presentacion = models.CharField(max_length=50)
    unidad_medida = models.CharField(max_length=50)
    lote = models.CharField(max_length=15, unique=True)
    cantidad = models.IntegerField()
    fecha_caducidad = models.DateField()
    fecha_ingreso = models.DateField(auto_now=True)

    def __unicode__(self):
    	return self.concepto

    class Meta:
    	ordering = ["-fecha_caducidad"]

academia/forms.py
from django import forms
from models import Comentario

class ComentarioForm(forms.ModelForm):
	usuario = forms.CharField(
		max_length = 30, 
		widget = forms.TextInput(
			attrs = {
				'class': 'form-control',
				'placeholder': 'Escribe tu nombre'
			})
		)
	
	comentario = forms.CharField(
		widget = forms.Textarea(
			attrs = {
				'class' : 'form-control',
				'rows': '4'
			})
		)

	class Meta:
		model = Comentario
		exclude = ["post"]

enfermeria/forms.py
from django import forms
from models import Medicamento

class MedicamentoForm(forms.ModelForm):
	concepto = forms.CharField(
		label = 'Concepto',
		widget = forms.TextInput(
			attrs = {
				'class' : 'form-control',
				'placeholder' : 'Paracetamol',
				'onkeyup' : 'this.value = this.value.toUpperCase()'
			})
	)

	lista_presentaciones = (
		('TABLETAS', 'Tabletas'),
		('TABLETAS RECUBIERTAS', 'Tabletas Recubiertas'),
		('SUSPENSION', 'Suspension'),
		('SUSPENSION AEROSOL', 'Suspension Aerosol'),
		('GRAGEAS', 'Grageas'),
		('CAPSULAS', 'Capsulas'),
		('COMPRIMIDOS', 'Comprimidos'),
		('CREMA', 'Crema'),
		('FRASCO', 'Frasco'),
		('SOL. INYECTABLE', 'Solucion Inyectable'),
		('PIEZA', 'Pieza')
	)

	presentacion = forms.ChoiceField(
		label = 'Presentacion',
		choices = lista_presentaciones,
		widget = forms.Select(
			attrs = {
				'class' : 'form-control',
			}
		)
	)

	unidad_medida = forms.CharField(
		label = 'Unidad de Medida',
		widget = forms.TextInput(
			attrs = {
				'class' : 'form-control',
				'placeholder' : '100 GRAMOS',
				'onkeyup' : 'this.value = this.value.toUpperCase()'
			})
	)

	lote = forms.CharField(
		label = 'Lote',
		widget = forms.TextInput(
			attrs = {
				'class' : 'form-control',
				'placeholder' : 'AB1005',
				'onkeyup' : 'this.value = this.value.toUpperCase()'
			})
	)

	cantidad = forms.CharField(
		label = 'Cantidad',
		widget = forms.TextInput(
			attrs = {
				'class' : 'form-control',
				'placeholder' : '100'
			})
	)

	fecha_caducidad = forms.DateField(
		label = 'Fecha de Caducidad',
		widget = forms.TextInput(
			attrs = {
				'class' : 'form-control',
				'placeholder' : '2015/01/01'
			})
	)

	class Meta:
		model = Medicamento
		exclude = ["fecha_ingreso"]

academia/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.core.paginator import Paginator
from django.core.context_processors import csrf

from django.views.generic import TemplateView, View, ListView, DetailView

from academia.models import Capitulo, Recurso, Post, Comentario
from academia.forms import ComentarioForm

class HomeView(TemplateView):
	template_name = "academia/index.html"

class CapituloListView(ListView):
	model = Capitulo
	template_name = "academia/capitulo_list.html"

class RecursoListView(ListView):
	model = Recurso
	template_name = "academia/recurso_list.html"

class PostListView(ListView):
    model = Post
    paginate_by = 2
    template_name = "academia/post_list.html"

def Post_detail(request, pk):
	post = Post.objects.get(pk=int(pk))
	comentarios = Comentario.objects.filter(post=post)
	form = ComentarioForm()
	dict_post = dict(post = post, comentarios = comentarios, form = form)
	dict_post.update(csrf(request))
	
	return render_to_response("academia/post.html",dict_post)

def Comentario_create(request, pk):
	p = request.POST
	comentario = Comentario(post=Post.objects.get(pk=pk))
	cf = ComentarioForm(p, instance=comentario)
	comentario = cf.save(commit=False)
	comentario.save()
	
	return HttpResponseRedirect(reverse('academia/post_detalles',args=[pk]))

enfermeria/views.py
from django.shortcuts import render, render_to_response
from django.views.generic import TemplateView

from forms import MedicamentoForm

class HomeView(TemplateView):
    template_name = "enfermeria/index.html"

class MenuView(TemplateView):
    template_name = "enfermeria/menu.html"

def Menu_index(request):
	form = MedicamentoForm()
	dict_menu = dict(medicamento = form ) 
	return render_to_response("enfermeria/menu.html",dict_menu)

academia/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Academia CISCO</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <!-- Barra de navegación -->
	{% include "navbar.html"  %}
    
    <!-- Contenido principal -->
    {% block content %}
    {% endblock %}
</body>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'formvalidation/dist/css/formValidation.min.css' %}">

	<link rel="stylesheet" href="{% static 'formvalidation/dist/css/formValidation.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

	<link rel="stylesheet" href="{% static 'fonts/open_sans.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/lora.css' %}">

	<script async src="{% static 'js/jquery.js' %}"></script>
	<script async src="{% static 'js/bootstrap.min.js' %}"></script>

	<script async src="{% static 'formvalidation/dist/js/formValidation.min.js' %}"></script>
	<script async src="{% static 'formvalidation/dist/js/framework/bootstrap.min.js' %}"></script>

	<script async src="{% static 'js/validaciones.js' %}"></script>
	<script async src="{% static 'js/clean-blog.min.js' %}"></script>
</html>

academia/templates/capitulo_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load django_markdown %}

{% block content %}
<!-- Page Header -->
<header class="intro-header" style="background-color: #FF9966">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="site-heading">
					<h1>Capítulos</h1>
					<hr class="small">
					<span class="subheading">Contenido del curso</span>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Capitulos del curso -->
<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<h1 class="page-header">IT Essentials</h1>
			{% for capitulo in object_list %}
				<h2 class="sub-header">
					<a id="{{ capitulo.id }}">{{ capitulo.titulo }}</a>
				</h2>
				{{ capitulo.objetivo|markdown }}
			{% endfor %}
			</div>
		</div>
</div>
<hr>
<br>
{% endblock %}

academia/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Page Header -->
<header class="intro-header" style="background-color: #FF9966">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="site-heading">
					<h1>Blog de Alumnos CIJ</h1>
					<hr class="small">
					<span class="subheading">Un portal para agilizar el aprendizaje.</span>
				</div>
			</div>
		</div>
	</div>
</header>
  
<!-- Contenido de la pagina -->
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h2>Capítulos de la Academia</h2>
			<p>Detalles y objetivos de los capítulos del curso. </p>
			<p><a class="btn btn-primary" href="/capitulos" role="button">Ver más &raquo;</a></p>
		</div>
		<div class="col-md-4">
			  <h2>Material Extra</h2>
			  <p>Vídeos, artículos y simuladores que te ayudaran a comprender los temas del curso. </p>
			  <p><a class="btn btn-primary" href="/material" role="button">Ver más &raquo;</a></p>
		   </div>
		<div class="col-md-4">
			  <h2>Blog</h2>
			  <p>Expresa tú opinión, colabora, contribuye, intercambia y comparte tus experiencias y dudas. </p>
			  <p><a class="btn btn-primary" href="/blog" role="button">Ver más &raquo;</a></p>
		</div>
	</div>
</div>
<hr>
<br>
{% endblock %}

academia/templates/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
	<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
					<a class="navbar-brand" href="/">Academia CISCO</a>
		</div>
<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="/capitulos">Capitulos</a>
					</li>
					<li>
						<a href="/material">Material</a>
					</li>
					<li>
						<a href="/blog">Blog</a>
					</li>
				</ul>
			</div>
	</div>
</nav>

academia/templates/post.html
{% extends "base.html" %}
{% load staticfiles %}
{% load django_markdown %}

{% block content %}
<!-- Page Header -->
<header class="intro-header" style="background-color:#FF9966">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="post-heading">
					<h1>{{post.encabezado}}</h1>
					<h2 class="subheading">{{post.usuario}}</h2>
					<p class="post-meta"> 
						<span class="glyphicon glyphicon-time"></span> {{ post.fecha }} 
					</p>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Contenido del Post -->
<article>
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				{{ post.cuerpo|markdown }}
			</div>
		</div>
	</div>
</article>
<hr>

<!-- Formulario-->
<div class="container">
	<div class="row">
	<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
		<div class="well">
		<h4>Deja un comentario:</h4>
			<form role="form" action="{% url 'comentario_crear' pk=post.id %}" method="POST" id="FormComentario">
				{% csrf_token %}
				<div class="form-group" >
					<div class="input-group">
						<span class="input-group-addon">
							<span class="glyphicon glyphicon-user"></span>
						</span>
							{{ form.usuario}}
					</div>
				</div>
					<div class="form-group">
						{{ form.comentario }}
					</div>
				<button type="submit" class="btn btn-primary">Enviar</button>
			</form>
		</div>
	<hr>
	<br>

<!-- Comentarios Publicados -->
		<div class="media">
			<div class="media-body">
			{% if comentarios %}		
				{% for comentario in comentarios %}
					<h4 class="media-heading">{{comentario.usuario}} - <small>{{comentario.fecha}}</small></h4>
					<p>{{comentario.comentario}}</p>
					<br>
				{% endfor %}
			{% else %}
				<h4>No hay comentarios</h4>
			{% endif %}
			</div>
		</div>
	</div>
	</div>
</div>
<hr>
<br>
{% endblock %}

academia/templates/post_list.html
{% extends "base.html" %}
{% load staticfiles %}
{% load django_markdown %}

{% block content %}
<!-- Page Header -->
<header class="intro-header" style="background-color: #FF9966">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="site-heading">
					<h1>Blog</h1>
					<hr class="small">
					<span class="subheading">Publicaciones recientes</span>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Publicaciones realizadas -->
<div class="container">
	<div class="row">
		<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
		<!-- Blog Post -->
		{% for post in object_list %}
			<div class="post-preview">
				<a href="{% url 'post_detalles' pk=post.id %}">
					<h2 class="post-title"> {{ post.encabezado }} </h2>
					<h3 class="post-subtitle"> {{ post.usuario }} </h3>
				</a>
				<p class="post-meta"> <span class="glyphicon glyphicon-time"></span> {{ post.fecha }} </p>
			</div>                
			<hr>
		{% endfor %}

		<!-- Paginador -->
		{% if is_paginated %}
			<ul class="pager">
			 {% if page_obj.has_previous %}
				<li class="previous">
					<a href="/blog?page={{page_obj.previous_page_number}}">&larr; Atrás</a>
				</li>
			{% endif %}
			{% if page_obj.has_next %}
				<li class="next">
					<a href="/blog?page={{page_obj.next_page_number}}">Siguiente &rarr;</a>
				</li>
			{% endif %}
			</ul>
		{% endif %}
		<br>
		</div>
	</div>
</div>
<hr>
<br>
{% endblock %}

academia/templates/recurso_list.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<!-- Page Header -->
<header class="intro-header" style="background-color: #FF9966">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="site-heading">
					<h1>Recursos</h1>
					<hr class="small">
					<span class="subheading">Material del curso</span>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Recursos de la academia -->
<div class="container">
	<div class="row">
	<h1 class="page-header">IT Essentials</h1>
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>#</th>
						<th>Capitulo</th>
						<th>Material</th>
						<th>URL</th>
					</tr>
				</thead>
				<tbody>
				{% for recurso in object_list %}
					<tr>
						<td>{{ recurso.id }}</td>
						<td>
							<a id="{{ recurso.id }}"> {{ recurso.capitulo }} </a>
						</td>
						<td>{{ recurso.descripcion }}</td>
						<td> 
							<a href="{{ recurso.url }}" target="_blank" > {{ recurso.url }} </a>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
<hr>
<br>
{% endblock %}

templates/academia/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Academia CISCO</title>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
</head>
<body>
    <!-- Barra de navegación -->
	{% include "academia/navbar.html"  %}
    
    <!-- Contenido principal -->
    {% block content %}
    {% endblock %}
</body>
	<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
	<link rel="stylesheet" href="{% static 'formvalidation/dist/css/formValidation.min.css' %}">

	<link rel="stylesheet" href="{% static 'formvalidation/dist/css/formValidation.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/clean-blog.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">

	<link rel="stylesheet" href="{% static 'fonts/open_sans.css' %}">
	<link rel="stylesheet" href="{% static 'fonts/lora.css' %}">

	<script async src="{% static 'js/jquery.min.js' %}"></script>
	<script async src="{% static 'js/bootstrap.min.js' %}"></script>

	<script async src="{% static 'formvalidation/dist/js/formValidation.min.js' %}"></script>
	<script async src="{% static 'formvalidation/dist/js/framework/bootstrap.min.js' %}"></script>

	<script async src="{% static 'js/validaciones.js' %}"></script>
	<script async src="{% static 'js/clean-blog.min.js' %}"></script>
</html>

templates/academia/capitulo_list.html
{% extends 'academia/base.html' %}
{% load staticfiles %}
{% load django_markdown %}

{% block content %}
<!-- Page Header -->
<header class="intro-header" style="background-color: #FF9966">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="site-heading">
					<h1>Capítulos</h1>
					<hr class="small">
					<span class="subheading">Contenido del curso</span>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Capitulos del curso -->
<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<h1 class="page-header">IT Essentials</h1>
			{% for capitulo in object_list %}
				<h2 class="sub-header">
					<a id="{{ capitulo.id }}">{{ capitulo.titulo }}</a>
				</h2>
				{{ capitulo.objetivo|markdown }}
			{% endfor %}
			</div>
		</div>
</div>
<hr>
<br>
{% endblock %}

templates/academia/frases.html
<div class="well">
	<h4>Frase del Día</h4>
	<p> <em>No podemos ver más que a corta distancia delante de nosotros, pero podemos ver claramente que hay mucho que hacer.   </em><strong>Alan Turing.</strong> </p>
</div>

templates/academia/index.html
{% extends 'academia/base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Page Header -->
<header class="intro-header" style="background-color: #FF9966">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="site-heading">
					<h1>Blog de Alumnos CIJ</h1>
					<hr class="small">
					<span class="subheading">Un portal para agilizar el aprendizaje.</span>
				</div>
			</div>
		</div>
	</div>
</header>
  
<!-- Contenido de la pagina -->
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<h2>Capítulos de la Academia</h2>
			<p>Detalles y objetivos de los capítulos del curso. </p>
			<p><a class="btn btn-primary" href="/academia/capitulos" role="button">Ver más &raquo;</a></p>
		</div>
		<div class="col-md-4">
			  <h2>Material Extra</h2>
			  <p>Vídeos, artículos y simuladores que te ayudaran a comprender los temas del curso. </p>
			  <p><a class="btn btn-primary" href="/academia/material" role="button">Ver más &raquo;</a></p>
		   </div>
		<div class="col-md-4">
			  <h2>Blog</h2>
			  <p>Expresa tú opinión, colabora, contribuye, intercambia y comparte tus experiencias y dudas. </p>
			  <p><a class="btn btn-primary" href="/academia/blog" role="button">Ver más &raquo;</a></p>
		</div>
	</div>
</div>
<hr>
<br>
{% endblock %}

templates/academia/menu.html
<div class="well">
	<h4>Categorias</h4>
	<div class="row">
		<div class="col-lg-6">
			<ul class="list-unstyled">
				<li> <a href="#">Crear Post</a> </li>
			</ul>
		</div> 
		<div class="col-lg-6">
			<ul class="list-unstyled">
				<li> <a href="#">Crear una Cuenta</a> </li>
			</ul>
		</div> 
	</div> 
</div>

templates/academia/navbar.html
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
	<div class="container-fluid">
<!-- Brand and toggle get grouped for better mobile display -->
		<div class="navbar-header page-scroll">
			<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
					<a class="navbar-brand" href="/academia">Academia CISCO</a>
		</div>
<!-- Collect the nav links, forms, and other content for toggling -->
		<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav navbar-right">
					<li>
						<a href="/academia/capitulos">Capitulos</a>
					</li>
					<li>
						<a href="/academia/material">Material</a>
					</li>
					<li>
						<a href="/academia/blog">Blog</a>
					</li>
				</ul>
			</div>
	</div>
</nav>

templates/academia/recurso_list.html
{% extends 'academia/base.html' %}
{% load staticfiles %}

{% block content %}
<!-- Page Header -->
<header class="intro-header" style="background-color: #FF9966">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
				<div class="site-heading">
					<h1>Recursos</h1>
					<hr class="small">
					<span class="subheading">Material del curso</span>
				</div>
			</div>
		</div>
	</div>
</header>

<!-- Recursos de la academia -->
<div class="container">
	<div class="row">
	<h1 class="page-header">IT Essentials</h1>
		<div class="table-responsive">
			<table class="table table-striped">
				<thead>
					<tr>
						<th>#</th>
						<th>Capitulo</th>
						<th>Material</th>
						<th>URL</th>
					</tr>
				</thead>
				<tbody>
				{% for recurso in object_list %}
					<tr>
						<td>{{ recurso.id }}</td>
						<td>
							<a id="{{ recurso.id }}"> {{ recurso.capitulo }} </a>
						</td>
						<td>{{ recurso.descripcion }}</td>
						<td> 
							<a href="{{ recurso.url }}" target="_blank" > {{ recurso.url }} </a>
						</td>
					</tr>
				{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
<hr>
<br>
{% endblock %}

templates/enfermeria/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <title>SICIJ</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style type="text/css" media="screen">
        hr{border-color: black; }
        h2 {text-align:center;}
        #medicamento_ok {color:green; font-size: 50px;}
        #user_gly {font-size: 28px;}
        #medicamento_remove {color:red; font-size: 50px;}
        .dropdown-toggle {font-size: 18px;}
        .nav.nav-tabs {font-size: 20px;}
    </style>
</head>
<body>
<div class="container" >
    <div class="masthead">
        <h3 class="text-muted" > 
            <img src="{% static 'images/CIJ.png' %}"> 
            <strong>
                Sistema de Información U.H. Punta Diamante
            </strong>
        </h3>
    </div>
    <hr>
    <br>
    {% block content %}
    {% endblock %}
</div>
</body>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.css'%}">
    <link rel="stylesheet" href="{% static 'formvalidation/dist/css/formValidation.min.css'%}">

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>

    <script src="{% static 'formvalidation/dist/js/formValidation.min.js' %}"></script>
    <script src="{% static 'formvalidation/dist/js/framework/bootstrap.min.js' %}"></script>

    <script type="text/javascript" src="{% static 'js/validar_medicina.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/validar_curacion.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/validar_inventario.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/validar_pdf.js' %}"></script>
    
    <script src="{% static 'js/jquery.uitablefilter.js' %}"></script>
    <script src="{% static 'js/buscar.js' %}"></script>

    <script type="text/javascript">
    $(function() {
        $( "#id_fecha_caducidad" ).datepicker();
    });
    $(function() {
        $( "#id_fecha_inicio" ).datepicker();
    });
    $(function() {
        $( "#id_fecha_final" ).datepicker();
    });
  </script>
</html>